//==================================
// W32SVSPY - Matt Pietrek 1995
// FILE: W32SVSPY.H
//==================================
#define ICON_1              1
#define IDC_LISTBOX_CALLS   100
#define IDC_BUTTON_START    101
#define IDC_BUTTON_STOP     102
#define IDC_BUTTON_EXIT     103
#define IDC_TEXT_STATUS     104
#define IDC_BUTTON_SAVE     105
#define IDC_BUTTON_FILTER   106

#define IDC_FILTER_LB_PROVIDERS 101
#define IDC_FILTER_LB_SERVICES      102

